### ISSUE TITLE
maybe we can avoid to build a mfext layer for integration tests

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext-integration-tests#7]
it should be possible in this repo to:

- install mfext as a regular RPM
- git cloning mfext sources to get sources of integration tests
- executing tests in this directory

see https://discourse.drone.io/t/cloning-additional-repos/763

With this workflow, we should avoid to compile/package mfext when we just add an integration test

**Comment by thefab** [comment]
@thebaptiste

**Comment by thefab** [comment]
it seems to work ?
feel free to close

**Comment by thebaptiste** [comment]
Closed. And this repository can be suppressed (or deactivated ?), replaced by mfext-integration-tests-runner.
